
<?php if( sizeof($this->getTotals()) > 0 ): ?>
    <?php foreach( $this->getTotals() as $_total ): ?>
    <div class="entry-edit" id="<?php echo str_replace(' ', '-', $_total['label']) ?>">
        <div class="entry-edit-head">
        	<h4>
        		<span class="label"><?php echo $_total['label'] ?></span>
        		<span class="main-kpi"><?php echo $_total['value'] ?></span>
        	</h4>
        </div>
        <div class="entry-edit-body group">
            <div class="chart"></div><ul class="past-data"></ul>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
